CentralParking/CentralParking/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CentralParking.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CentralParking/CentralParking/Controllers/LocadorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CentralParking.Models;

namespace CentralParking.Controllers
{
    public class LocadorsController : Controller
    {
        private CentralParkingEntities db = new CentralParkingEntities();

        // GET: Locadors
        public ActionResult Index()
        {
            return View(db.Locador.ToList());
        }

        // GET: Locadors/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Locador locador = db.Locador.Find(id);
            if (locador == null)
            {
                return HttpNotFound();
            }
            return View(locador);
        }

        // GET: Locadors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Locadors/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Dono,Nome_Dono,CPF,email,usuario,senha,Tipo")] Locador locador)
        {
            if (ModelState.IsValid)
            {
                db.Locador.Add(locador);
                try
                {
                    db.SaveChanges();
                } catch (DbEntityValidationException e)
                {
                    foreach(var eve in e.EntityValidationErrors)
                    {
                        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                            eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        foreach(var ve in eve.ValidationErrors)
                        {
                            Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"", ve.PropertyName, ve.ErrorMessage);
                        }
                        
                    }
                    throw;
                }
                return RedirectToAction("Index");
            }

            return View(locador);
        }

        // GET: Locadors/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Locador locador = db.Locador.Find(id);
            if (locador == null)
            {
                return HttpNotFound();
            }
            return View(locador);
        }

        // POST: Locadors/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Dono,Nome_Dono,CPF,email,usuario,senha,Tipo")] Locador locador)
        {
            if (ModelState.IsValid)
            {
                db.Entry(locador).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(locador);
        }

        // GET: Locadors/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Locador locador = db.Locador.Find(id);
            if (locador == null)
            {
                return HttpNotFound();
            }
            return View(locador);
        }

        // POST: Locadors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            Locador locador = db.Locador.Find(id);
            db.Locador.Remove(locador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CentralParking/CentralParking/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CentralParking/CentralParking/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CentralParking/CentralParking/Views/Home/Index.cshtml
@{
    Layout = null;
}



<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="author" content="Roger">

<title>Central Parking</title>

<link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="~/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
<link rel="stylesheet" href="~/Content/vendor/simple-line-icons/css/simple-line-icons.css">
<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
<link rel="stylesheet" href="~/Content/device-mockups/device-mockups.min.css">
<link href="~/Content/css/new-age.min.css" rel="stylesheet">


<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container" id="page-top">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Central Parking</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#download">APP</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#sobre">Sobre</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#cadastro">Cadastro</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#contato">Contato</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<header class="masthead">
    <div class="container h-100">
        <div class="row h-100">
            <div class="col-lg-7 my-auto">
                <div class="header-content mx-auto">
                    <h1 class="mb-5">Saia na frente, estacione sem procurar vagas deixe que o aplicativo CentralParking procure por você!</h1>
                    <a href="#download" class="btn btn-outline btn-xl js-scroll-trigger">Teste Agora Grátis!</a>
                </div>
            </div>
            <div class="col-lg-5 my-auto">
                <div class="device-container">
                    <div class="device-mockup iphone6_plus portrait white">
                        <div class="device">
                            <div class="screen">

                                <img src="~/Content/img/demo-screen-1.jpg" class="img-fluid" alt="">
                            </div>
                            <div class="button">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<section class="download bg-primary text-center" id="download">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <h2 class="section-heading">Descubra tudo sobre!</h2>
                <p>Nosso app está disponível apenas para android! Baixe agora para testar</p>
                <div class="badges">
                    <a class="badge-link" href="#"><img src="~/Content/img/google-play-badge.svg" alt=""></a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="features" id="sobre">
    <div class="container">
        <div class="section-heading text-center">
            <h2>Nada de gastar gasolina, ache sua vaga em poucos segundos</h2>
            <p class="text-muted">Rápido e sem complicações</p>
            <hr>
        </div>
        <div class="row">
            <div class="col-lg-4 my-auto">
                <div class="device-container">
                    <div class="device-mockup iphone6_plus portrait white">
                        <div class="device">
                            <div class="screen">
                                <img src="~/Content/img/demo-screen-1.jpg" class="img-fluid" alt="">
                            </div>
                            <div class="button">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 my-auto">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="feature-item">
                                <i class="icon-calendar text-primary"></i>
                                <h3>Agendamento</h3>
                                <p class="text-muted">Agende para quando achar melhor, escolha a data de acordo com sua necessidade!</p>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="feature-item">
                                <i class="icon-direction text-primary"></i>
                                <h3>Facilidade no Uso</h3>
                                <p class="text-muted">Não pense, o app fará a maior parte!</p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="feature-item">
                                <i class="icon-present text-primary"></i>
                                <h3>Grátis para Uso</h3>
                                <p class="text-muted">App totalmente gratuito para todos!</p>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="feature-item">
                                <i class="icon-lock text-primary"></i>
                                <h3>Segurança</h3>
                                <p class="text-muted">App e site com total segurança na hora de pagamento!</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="cta">
    <div class="cta-content" id="cadastro">
        <div class="container">
            <h2>Quer colocar sua vaga online?<br>Cadastre-se</h2>
            @Html.ActionLink("Cadastro", "Create", "Locadors", new { area = "" }, new { @class = "btn btn-outline btn-xl js-scroll-trigger" })
        </div>
    </div>
    <div class="overlay"></div>
</section>

<section class="contact bg-primary" id="contato">
    <div class="container">
        <h2>
            Entre em contato com a gente!
        </h2>
        <ul class="list-inline list-social">
            <li class="list-inline-item social-twitter">
                <a href="#">
                    <i class="fab fa-twitter"></i>
                </a>
            </li>
            <li class="list-inline-item social-facebook">
                <a href="#">
                    <i class="fab fa-facebook-f"></i>
                </a>
            </li>
            <li class="list-inline-item social-google-plus">
                <a href="#">
                    <i class="fab fa-google-plus-g"></i>
                </a>
            </li>
        </ul>
    </div>
</section>

<footer>
    <div class="container">
        <p>&copy; Central Parking 2019. TCC QUERO PASSAR.</p>
    </div>
</footer>


<script src="~/Content/vendor/jquery/jquery.min.js"></script>
<script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/Content/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="~/Content/js/new-age.min.js"></script>

